name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check out repository code
      uses: actions/checkout@v4

  discord:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Discord Commits
      uses: Sniddl/discord-commits@v1.6
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        template: "avatar-with-link"
        include-extras: true


  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Test with pytest
      run:
        pip install pytest pytest-cov
        pytest test/test.py
