name: Continuous delivery

on:
  push:
    branches: [ "main" ]

jobs:
  deliver:

    runs-on: ubuntu-latest

    steps:
    - name: check out repository code
      uses: actions/checkout@v4

    - name: simulando CD
      uses: actions/upload-artifact@v4
      with:
        name: my-test-zip.zip
        path: |
          CinemaIngressos.cpp
          '**.lib'
          README.nd

  deployment:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-test-zip.zip
      - name: Display structure of downloaded files
        run: ls -R
